# Generated by Django 2.2.2 on 2019-06-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpresaProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
