# Generated by Django 2.2.2 on 2019-06-21 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudanteProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universidade', models.CharField(blank=True, max_length=10)),
                ('curso', models.CharField(blank=True, max_length=50)),
                ('previsao_de_formatura', models.IntegerField(null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(default='profile-placeholder.png', upload_to='student-profile_pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
