# Generated by Django 2.2.2 on 2019-06-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstudanteProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudanteprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
    ]
