# Generated by Django 2.2.2 on 2019-06-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstudanteProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudanteprofile',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
