# Generated by Django 2.2.1 on 2019-05-31 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmpresaProfile', '0001_initial'),
        ('EstudanteProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('pagamento', models.FloatField()),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpresaProfile.EmpresaProfile')),
                ('inscritos', models.ManyToManyField(to='EstudanteProfile.EstudanteProfile')),
            ],
        ),
    ]
