# Generated by Django 2.2.2 on 2019-06-21 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmpresaProfile', '0001_initial'),
        ('EstudanteProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('pagamento', models.FloatField()),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField()),
                ('private', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trabalho', to='EmpresaProfile.EmpresaProfile')),
                ('contratados', models.ManyToManyField(blank=True, related_name='contratados', to='EstudanteProfile.EstudanteProfile')),
                ('inscritos', models.ManyToManyField(blank=True, related_name='subscribers', to='EstudanteProfile.EstudanteProfile')),
            ],
        ),
    ]
