# Generated by Django 2.2.1 on 2019-05-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trabalhos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='inscritos',
            field=models.ManyToManyField(blank=True, null=True, to='EstudanteProfile.EstudanteProfile'),
        ),
    ]
