# Generated by Django 2.2.2 on 2019-06-08 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trabalhos', '0003_auto_20190531_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EmpresaProfile.EmpresaProfile'),
        ),
    ]
