# Generated by Django 2.2.2 on 2019-06-09 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EstudanteProfile', '0001_initial'),
        ('Trabalhos', '0004_auto_20190608_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='contratados',
            field=models.ManyToManyField(blank=True, related_name='contratados', to='EstudanteProfile.EstudanteProfile'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trabalho', to='EmpresaProfile.EmpresaProfile'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='inscritos',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='EstudanteProfile.EstudanteProfile'),
        ),
    ]
