# Generated by Django 2.2.2 on 2019-06-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trabalhos', '0005_auto_20190609_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
