# Generated by Django 2.2.2 on 2019-06-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trabalhos', '0006_trabalho_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
